version: '3.8'

services:
  comfyui:
    build:
      context: ./multimodal_services/ComfyUI
      dockerfile: ../../Dockerfile.comfyui
    ports:
      - "8188:8188"
    volumes:
      - ./multimodal_services/ComfyUI/models:/app/models
      - ./multimodal_services/ComfyUI/output:/app/output
      - ./multimodal_services/ComfyUI/input:/app/input
      - ./multimodal_services/ComfyUI/custom_nodes:/app/custom_nodes
      - ./pareng_boyong_deliverables:/app/deliverables
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONPATH=/app
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8188/system_stats"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Optional: Video processing service
  video-processor:
    build:
      context: ./multimodal_services
      dockerfile: ../Dockerfile.video-processor
    ports:
      - "8189:8189"
    volumes:
      - ./pareng_boyong_deliverables:/app/deliverables
    environment:
      - COMFYUI_URL=http://comfyui:8188
      - PYTHONPATH=/app
    depends_on:
      comfyui:
        condition: service_healthy
    restart: unless-stopped

networks:
  default:
    name: pareng-boyong-multimodal